version: '3.1'

services:
  api:
    image: osu_api
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432

  bot:
    build:
      context: .
      dockerfile: ./bot-docker/Dockerfile
    depends_on:
      - db
    links:
      - db
      - api